# fly.toml app configuration file generated for waskrabbeltda-api on 2024-05-10T11:10:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'waskrabbeltda-api'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source="data"
  destination="/fastapi/data"
  auto_extend_size_threshold = 80 #80% of disk capacity reached
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "3GB" #end of free disk space